"""UI launcher for AIND Data Transfer Lite."""

from pathlib import Path
from typing import get_origin

from magicclass import magicclass
from magicgui import widgets
from pydantic import DirectoryPath
from qtpy import QtWidgets

from aind_data_transfer_lite.models import JobSettings


@magicclass(layout="vertical", labels=True)
class JobSettingsForm:
    """Form for editing JobSettings."""

    def __init__(self):
        """Initialize the JobSettings form and create all UI elements."""
        self.field_widgets = {}

        # -------------------------------
        # Autogenerate all fields except modality_directories
        # -------------------------------
        for name, field in JobSettings.model_fields.items():
            if name == "modality_directories":
                continue  # handled separately

            label = field.title or field.alias
            if not field.is_required():
                label += " (Optional)"

            # Safe type check for DirectoryPath / Path
            origin = get_origin(field.annotation)
            if origin is None and field.annotation in (DirectoryPath, Path):
                widget = widgets.FileEdit(label=label, mode="d")
            elif field.annotation is bool:
                widget = widgets.CheckBox(label=label, value=field.default)
            elif field.annotation is str:
                widget = widgets.LineEdit(label=label, value=field.default)
            else:
                continue  # unsupported type

            self.field_widgets[name] = widget
            # Disable tooltips to prevent showing docstring as fallback
            widget.native.setToolTip("")


        # -------------------------------
        # Modality UI
        # -------------------------------
        self.modality_container = widgets.Container(layout="vertical")
        self.modality_container.append(self._make_modality_row())
        self.append(self.modality_container)

        self.add_modality_btn = widgets.PushButton(text="Add Modality")
        self.add_modality_btn.clicked.connect(self._add_modality_row)
        self.append(self.add_modality_btn)

        # -------------------------------
        # Append all autogenerated fields after Add Modality
        # -------------------------------
        for name, widget in self.field_widgets.items():
            self.append(widget)

        # -------------------------------
        # Output + Buttons
        # -------------------------------
        self.output_box = widgets.TextEdit(label="Output")
        self.output_box.native.setReadOnly(True)
        self.append(self.output_box)

        self.copy_btn = widgets.PushButton(text="Copy Input")
        self.append(self.copy_btn)
        self.copy_btn.clicked.connect(self._copy_output)

        self.submit_btn = widgets.PushButton(text="Submit")
        self.append(self.submit_btn)

        self.clear_btn = widgets.PushButton(text="Clear")
        self.append(self.clear_btn)
        self.clear_btn.clicked.connect(self._clear_form)

    # -------------------------------
    # Modality row (buttons only)
    # -------------------------------
    def _add_modality_row(self):
        """Append a new modality row to the modality container."""
        self.modality_container.append(self._make_modality_row())

    def _make_modality_row(self):
        """Creates a single modality row with dropdown, directory picker,
        and delete button.
        """
        dropdown = widgets.ComboBox(
            label="Modality",
            choices=JobSettings._modality_abbreviations,
        )
        picker = widgets.FileEdit(label="Directory", mode="d")
        delete_btn = widgets.PushButton(text="Delete")

        row = widgets.Container(
            widgets=[dropdown, picker, delete_btn],
            layout="horizontal",
        )

        # Connect delete to row-specific handler
        delete_btn.clicked.connect(lambda: self._delete_modality_row(row))

        return row
    def _delete_modality_row(self, row):
        """Delete a modality row unless it's the last remaining row."""
        if len(self.modality_container) <= 1:
            return  # Prevent deleting the final row
        self.modality_container.remove(row)

    def _copy_output(self):
        """Copy the current output box contents to the system clipboard."""
        text = self.output_box.value or "" # fallback to empty string
        QtWidgets.QApplication.clipboard().setText(text)

    def _clear_form(self):
        """Reset the form to default values."""
        # Reset autogenerated fields
        for name, field in JobSettings.model_fields.items():
            if name == "modality_directories":
                continue
            widget = self.field_widgets[name]
            if field.annotation in (DirectoryPath, Path):
                widget.value = ""
            elif field.annotation is bool:
                widget.value = field.default
            elif field.annotation is str:
                widget.value = field.default

        # Reset modality container to a single default row
        self.modality_container.clear()
        self.modality_container.append(self._make_modality_row())

        # Clear output box
        self.output_box.value = ""

if __name__ == "__main__":
    gui = JobSettingsForm()
    gui.native.setWindowTitle("AIND Data Transfer Lite")
    gui.show(run=True)
