from pathlib import Path
from typing import get_origin

from magicclass import magicclass
from magicgui import widgets
from models import JobSettings
from pydantic import DirectoryPath


@magicclass(layout="vertical", labels=True)
class JobSettingsForm:
    def __init__(self):
        self.field_widgets = {}

        # -------------------------------
        # Autogenerate all fields except modality_directories
        # -------------------------------
        for name, field in JobSettings.model_fields.items():
            if name == "modality_directories":
                continue  # handled separately

            label = field.title or field.alias
            if not field.is_required():
                label += " (Optional)"

            # Safe type check for DirectoryPath / Path
            origin = get_origin(field.annotation)
            if origin is None and field.annotation in (DirectoryPath, Path):
                widget = widgets.FileEdit(label=label, mode="d")
            elif field.annotation is bool:
                widget = widgets.CheckBox(label=label, value=field.default)
            elif field.annotation is str:
                widget = widgets.LineEdit(label=label, value=field.default)
            else:
                continue  # unsupported type

            self.field_widgets[name] = widget

        # -------------------------------
        # Modality UI
        # -------------------------------
        self.modality_container = widgets.Container(layout="vertical")
        self.modality_container.append(self._make_modality_row())
        self.append(self.modality_container)

        self.add_modality_btn = widgets.PushButton(text="Add Modality")
        self.append(self.add_modality_btn)

        # -------------------------------
        # Append other autogenerated fields after Add Modality
        # Keeps Pydantic ordering except modality_directories
        # -------------------------------
        for name, widget in self.field_widgets.items():
            if name == "modality_directories":
                continue
            self.append(widget)

        # -------------------------------
        # Output + Buttons
        # -------------------------------
        self.output_box = widgets.TextEdit(label="Output")
        self.output_box.native.setReadOnly(True)
        self.append(self.output_box)

        self.copy_btn = widgets.PushButton(text="Copy Input")
        self.append(self.copy_btn)

        self.submit_btn = widgets.PushButton(text="Submit")
        self.append(self.submit_btn)

        self.clear_btn = widgets.PushButton(text="Clear")
        self.append(self.clear_btn)

    # -------------------------------
    # Modality row (buttons only)
    # -------------------------------
    def _make_modality_row(self):
        dropdown = widgets.ComboBox(
            label="Modality",
            choices=JobSettings._modality_abbreviations,
        )
        picker = widgets.FileEdit(label="Directory", mode="d")
        delete_btn = widgets.PushButton(text="Delete")

        return widgets.Container(
            widgets=[dropdown, picker, delete_btn],
            layout="horizontal",
        )


if __name__ == "__main__":
    gui = JobSettingsForm()
    gui.native.setWindowTitle("AIND Data Transfer Lite")
    gui.show(run=True)
